# hadolint global ignore=DL3007,DL3041,DL3059,DL4006
# - 3007 - yes, I do want the `latest` :D
# - 3041 - no, I don't care about specific versions of the packages I'm installing
# - 3059 - I'm ok with consecutive `RUN`s; I squash the layers at the end regardless,
#          and during the build multiple `RUN` lines cache better
# - 4006 - podman doesn't support this :[

FROM fedora:latest AS base-builder
# Set up my user
ARG UID=1000
ARG GID=1000
RUN groupadd -g ${GID} yacoob \
  && useradd -l -u ${UID} -g ${GID} -m -s /usr/bin/zsh -G wheel yacoob \
  && passwd -d yacoob
# Install packages
RUN \
  for c in atim/bottom atim/lazygit atim/starship faramirza/gdu; do \
    dnf5 copr enable -y $c; \
  done \
  && dnf5 install --setopt=install_weak_deps=False -y \
    bat curl difftastic fd-find fzf git procps psmisc ripgrep sudo tealdeer unzip yq which zsh \
    gdu bottom starship \
  && dnf5 clean all
# install eget
WORKDIR /usr/bin
RUN curl https://zyedidia.github.io/eget.sh | sh
# install chezmoi + modify_manager
RUN ./eget twpayne/chezmoi -a chezmoi-linux -a '^musl' --to=/usr/bin \
  && ./eget VorpalBlade/chezmoi_modify_manager -a gnu --to=/usr/bin
# The context should contain the entire repository.
COPY --chown=yacoob:yacoob . /home/yacoob/.local/share/chezmoi
USER yacoob
WORKDIR /home/yacoob
# Run chezmoi install script
RUN touch ~/zellij-inhibit && ./.local/share/chezmoi/install.sh
# start zsh so antidote can install plugins
RUN  script -qec '/usr/bin/zsh -is </dev/null' /dev/null


FROM base-builder AS devenv-builder
USER root
# Add more packages
RUN dnf5 install --setopt=install_weak_deps=False -y \
    direnv gcc gh just lazygit libicu neovim nodejs-npm tmux \
  && dnf5 clean all
# install binaries via eget
RUN /usr/bin/eget watchexec/watchexec -a musl.tar.xz _ -a '^b3' -a '^sha512' --to=/usr/local/bin \
  && /usr/bin/eget zellij-org/zellij --to=/usr/local/bin
USER yacoob


FROM fedora:latest AS common
# Set the environment
ENV SHELL=/usr/bin/zsh
ENV SSH_AUTH_SOCK=/home/yacoob/.ssh/agent.sock
ENV TERM=xterm-256color
ENV TZ='Europe/Dublin'
USER yacoob
WORKDIR /home/yacoob
ENTRYPOINT ["/usr/bin/zsh"]
LABEL maintainer="yacoob@ftml.net"
# Add devcontainer options
# https://containers.dev/implementors/reference/#labels
LABEL devcontainer.metadata='{ \
  "remoteUser": "yacoob", \
  "containerUser": "yacoob", \
  "securityOpt": ["label=disable"] \
}'


FROM common AS base
COPY --from=base-builder / /


FROM common AS devenv
COPY --from=devenv-builder / /
