# hadolint global ignore=DL3007,DL3041,DL3059,DL4006
# - 3007 - yes, I do want the `latest` :D
# - 3041 - no, I don't care about specific versions of the packages I'm installing
# - 3059 - I'm ok with consecutive `RUN`s; I squash the layers at the end regardless,
#          and during the build multiple `RUN` lines cache better
# - 4006 - podman doesn't support this :[

FROM fedora:latest AS base-builder
# Set up my user
ARG UID=1000
ARG GID=1000
RUN groupadd -g ${GID} yacoob \
  && useradd -l -u ${UID} -g ${GID} -m -s /usr/bin/zsh -G wheel yacoob \
  && passwd -d yacoob
# Install packages
RUN \
  dnf5 install --setopt=install_weak_deps=False -y \
    curl \
    fd-find \
    fzf \
    gdu \
    git \
    procps \
    psmisc \
    ripgrep \
    sudo \
    tealdeer \
    unzip \
    util-linux \
    util-linux-script \
    which \
    zsh \
  && dnf5 clean all
# install soar and use it to fetch more binaries
USER yacoob
WORKDIR /home/yacoob
RUN curl -fsSL https://soar.qaidvoid.dev/install.sh | sh \
  && ./.local/bin/soar install \
    bottom \
    chezmoi \
    chezmoi_modify_manager \
    eget#github.com.zyedidia.eget:bincache \
    eza#github.com.eza-community.eza:bincache \
    starship#github.com.starship.starship:bincache \
  && ./.local/bin/soar clean \
  && rm -rf ./.local/share/soar/repos
# The context should contain the entire repository.
COPY --chown=yacoob:yacoob . /home/yacoob/.local/share/chezmoi
# Run chezmoi install script
RUN touch ~/zellij-inhibit && PATH=~/.local/share/soar/bin:$PATH ./.local/share/chezmoi/install.sh
# start zsh so antidote can install plugins
RUN  script -qec '/usr/bin/zsh -is </dev/null' /dev/null


FROM base-builder AS devenv-builder
USER root
# Add more packages
RUN dnf5 install --setopt=install_weak_deps=False -y \
    bat \
    difftastic \
    direnv \
    gcc \
    gh \
    git-credential-oauth \
    just \
    libicu \
    neovim \
    nodejs-npm \
    yq \
  && dnf5 clean all
# install binaries via soar
USER yacoob
WORKDIR /home/yacoob
RUN ./.local/bin/soar install \
      fswatcher \
      lazygit#github.com.jesseduffield.lazygit:bincache \
      viddy \
      zellij \
    && ./.local/bin/soar clean


FROM fedora:latest AS base
COPY --from=base-builder / /
# Set the environment
ENV SHELL=/usr/bin/zsh
ENV SSH_AUTH_SOCK=/home/yacoob/.ssh/agent.sock
ENV TERM=xterm-256color
ENV TZ='Europe/Dublin'
USER yacoob
WORKDIR /home/yacoob
ENTRYPOINT ["/usr/bin/zsh"]
LABEL maintainer="yacoob@ftml.net"
# Add devcontainer options
# https://containers.dev/implementors/reference/#labels
LABEL devcontainer.metadata='{ \
  "remoteUser": "yacoob", \
  "containerUser": "yacoob", \
  "securityOpt": ["label=disable"] \
  "prompt": "podman run -it --rm --userns=keep-id:uid=1000,gid=1000 --security-opt label=disable -v /home/yacoob/.ssh:/home/yacoob/.ssh:ro IMAGE" \
}'


FROM base AS devenv
COPY --from=devenv-builder / /
