[custom_commands."move commit down"]
key = ["ctrl+j"]
args = ["rebase", "-r", "$change_id", "--insert-before", "$change_id-"]

[custom_commands."move commit up"]
key = ["ctrl+k"]
args = ["rebase", "-r", "$change_id", "--insert-after", "$change_id+"]
