name: Build and push image to Docker Hub

on:
  # Build for all git pushes, push and mark as 'latest' only for
  # main branch.
  push:
  # For pull requests, build but don't push.
  pull_request:
  # Build and push if triggered manually.
  workflow_dispatch:

jobs:
  build:
    name: Build and optionally push the image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Work out docker tags
        uses: docker/metadata-action@v5
        id: docker_meta
        with:
          images: yacoob/interactive
          tags: |
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Set branch name as env variable
        run: |
          export _BRANCH=${{ github.head_ref || github.ref }}
          echo "CONF_BRANCH=${_BRANCH##*/}" >> $GITHUB_ENV
      - name: Debug dump
        uses: crazy-max/ghaction-dump-context@v2
      - name: Set up docker builder (buildx)
        uses: docker/setup-buildx-action@v3
      - name: Log in to docker hub
        # Skip registry push for pull_requests.
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and optionally push the base version
        uses: docker/build-push-action@v6
        with:
          target: base
          context: .
          file: .local/share/dotfiles-docker/Dockerfile
          build-args: |
            CONF_BRANCH=${{ env.CONF_BRANCH }}
          # Push to registry only for main branch pushes.
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
            yacoob/interactive:base
      - name: Build and optionally push the nvim version
        uses: docker/build-push-action@v6
        with:
          target: nvim
          context: .
          file: .local/share/dotfiles-docker/Dockerfile
          build-args: |
            CONF_BRANCH=${{ env.CONF_BRANCH }}
          # Push to registry only for main branch pushes.
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          tags: |
            ${{ steps.docker_meta.outputs.tags }}
            yacoob/interactive:nvim

  ping-others:
    name: Notify other repositories about new version of the base image.
    runs-on: ubuntu-latest
    # Only ping others on pushes to main branch.
    if: github.event_name == 'push' && endsWith(github.ref, '/main')
    # Don't ping if build step failed.
    needs: build
    steps:
      - name: Ping yacoob/docker-beets
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          repository: yacoob/docker-beets
          event-type: dependency-updated
