name: Build and push an image to GitHub Container Registry

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: yacoob/interactive
  SHOULD_PUSH: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') }}

jobs:
  build:
    name: Build and optionally push ${{ matrix.target }} image
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        target: [base, devenv]

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Set image names
        run: |
          echo "TARGET=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Work out container tags
        uses: docker/metadata-action@v5
        id: tags
        with:
          images: ${{ env.TARGET }}
          tags: |
            type=sha,suffix=-${{ matrix.target }}
            type=raw,value=${{ matrix.target }},enable={{ is_default_branch }}

      - name: Cache buildah layers
        uses: actions/cache@v4
        with:
          path: ~/.local/share/containers/storage
          key: buildah-layers-${{ hashFiles('container/Containerfile') }}

      - name: Build the ${{ matrix.target }} version
        uses: redhat-actions/buildah-build@v2
        id: build
        with:
          containerfiles: ./container/Containerfile
          context: .
          extra-args: --target=${{ matrix.target }}
          layers: true
          labels: ${{ steps.tags.outputs.labels }}
          tags: ${{ steps.tags.outputs.tags }}

      - name: Log in to GitHub Container Registry
        if: ${{ env.SHOULD_PUSH == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push the ${{ matrix.target }} version
        if: ${{ env.SHOULD_PUSH == 'true' }}
        id: push
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ${{ steps.build.outputs.tags }}

      - name: Generate artifact attestation
        if: ${{ env.SHOULD_PUSH == 'true' }}
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.TARGET }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Notify dependent repositories
        if: ${{ env.SHOULD_PUSH == 'true' && matrix.target == 'base' }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          repository: yacoob/beets-container
          event-type: dependency-updated
