name: Build and push an image to GitHub Container Registry

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: yacoob/interactive
  CACHE_TARGET: ghcr.io/yacoob/interactive
  SHOULD_PUSH: ${{ (github.event_name == 'push' && github.ref == 'refs/heads/main') }}

jobs:
  build:
    name: Build container images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Set image names
        run: |
          echo "TARGET=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Work out base version tags
        uses: docker/metadata-action@v5
        id: base-tags
        with:
          images: ${{ env.TARGET }}
          tags: |
            type=sha,suffix=-base
            type=raw,value=base,enable={{ is_default_branch }}

      - name: Work out devenv version tags
        uses: docker/metadata-action@v5
        id: devenv-tags
        with:
          images: ${{ env.TARGET }}
          tags: |
            type=sha,suffix=-devenv
            type=raw,value=devenv,enable={{ is_default_branch }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the base version
        uses: redhat-actions/buildah-build@v2
        id: build-base
        with:
          containerfiles: ./container/Containerfile
          context: .
          extra-args: --target=base --cache-from ${{ env.CACHE_TARGET }} --cache-to ${{ env.CACHE_TARGET }}
          layers: true
          labels: ${{ steps.base-tags.outputs.labels }}
          tags: ${{ steps.base-tags.outputs.tags }}

      - name: Build the devenv version
        uses: redhat-actions/buildah-build@v2
        id: build-devenv
        with:
          containerfiles: ./container/Containerfile
          context: .
          extra-args: --target=devenv --cache-from ${{ env.CACHE_TARGET }} --cache-to ${{ env.CACHE_TARGET }}
          layers: true
          labels: ${{ steps.devenv-tags.outputs.labels }}
          tags: ${{ steps.devenv-tags.outputs.tags }}

      - name: Push the base version
        if: ${{ env.SHOULD_PUSH == 'true' }}
        id: push-base
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ${{ steps.build-base.outputs.tags }}

      - name: Push the devenv version
        if: ${{ env.SHOULD_PUSH == 'true' }}
        id: push-devenv
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ${{ steps.build-devenv.outputs.tags }}

      - name: Generate artifact attestation for base
        if: ${{ env.SHOULD_PUSH == 'true' }}
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.TARGET }}
          subject-digest: ${{ steps.push-base.outputs.digest }}
          push-to-registry: true

      - name: Generate artifact attestation for devenv
        if: ${{ env.SHOULD_PUSH == 'true' }}
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.TARGET }}
          subject-digest: ${{ steps.push-devenv.outputs.digest }}
          push-to-registry: true

      - name: Notify dependent repositories
        if: ${{ env.SHOULD_PUSH == 'true' }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          repository: yacoob/beets-container
          event-type: dependency-updated
